services:
  app:
    image: node:16
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    working_dir: /app
    env_file:
      - '.env'
    command: yarn dev:api
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0-oracle
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql -schemas="$MYSQL_DATABASE" -user=root -connectRetries=60 migrate
    volumes:
      - ./resources/migrations:/flyway/sql
    depends_on:
      - mysql
